export const LIVE_FETCH_DATA_SOURCE_KEYS = [
  "usgs_earthquake",
  "noaa_swpc_flare",
  "noaa_swpc_kp",
  "nhc_active_storms",
  "noaa_ndbc",
  "openfda_food_enforcement",
  "cpsc_recalls",
  "sec_edgar_submissions",
  "bls_cpi",
  "bls_unrate",
  "courtlistener_recap",
  "npm_registry_package",
  "dockerhub_tags",
  "pypi_json",
  "wikimedia_pageviews",
  "arxiv_api",
  "crossref_works",
  "hn_firebase",
  "stackexchange_questions",
  "steam_current_players",
  "apple_rss_top_apps",
  "github_releases",
  "cloudflare_dns_over_https",
  "crtsh_certificate_transparency",
  "http_robots_txt",
  "rss_atom_feed",
] as const;

export const LIVE_FETCH_DATA_SOURCE_KEY_SET = new Set<string>(LIVE_FETCH_DATA_SOURCE_KEYS);
